In [1]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [37]:
a = np.random.random((3,3,3))
print (a)

[[[0.24177814 0.8546347  0.04659965]
  [0.54609769 0.84421542 0.89836355]
  [0.77328933 0.68594524 0.72240755]]

 [[0.5118464  0.13964287 0.47614956]
  [0.39195425 0.74247768 0.91413087]
  [0.87462717 0.60567423 0.07740829]]

 [[0.23984278 0.25763595 0.22300321]
  [0.06596196 0.20283177 0.00357034]
  [0.83799863 0.08155022 0.84593257]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [35]:
# k indicates the position of the diagonal

b = np.diag(1+np.arange(4),k=-1)

print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [34]:
c = np.zeros((8,8),dtype=int)

c[1::2,::2] = 1 # Slice from 1st index row till 1+2+2… and fill all columns with 1 starting from 0th to 0+2+2...

c[::2,1::2] = 1 # Slice from 0th row till 0+2+2… and fill all columns with 1 starting from 1 to 1+2+2...

print (c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [33]:
d = np.random.random((5,5))
print ('Before Normalizing\n')
print (d,'\n')

max, min = d.max(), d.min()

d_normal = (d - min)/(max - min)

print ('After Normalizing\n')
print(d_normal)

Before Normalizing

[[0.32247656 0.25836045 0.44450366 0.29465986 0.09012967]
 [0.21620305 0.6470634  0.26648589 0.7519751  0.29903216]
 [0.99933295 0.13681733 0.31977607 0.21740342 0.41414847]
 [0.23118259 0.64973432 0.56435025 0.05124107 0.22905345]
 [0.53294874 0.47733557 0.9690709  0.58282746 0.5268203 ]] 

After Normalizing

[[0.28608566 0.21845918 0.41479375 0.25674599 0.04101776]
 [0.17399366 0.62844366 0.22702949 0.73909929 0.26135768]
 [1.         0.09026157 0.28323732 0.17525976 0.38277661]
 [0.18979333 0.63126082 0.54120196 0.         0.18754763]
 [0.50808122 0.44942321 0.9680811  0.5606908  0.50161724]]


# 5.  How to find common values between two arrays?

In [32]:
e1 = np.random.randint(0,50,10)
e2 = np.random.randint(0,50,10)

print (e1)
print (e2)
print(np.intersect1d(e1,e2))

[43 49 39 24  5 18  9  8  0  2]
[ 4  6 42  9 18 38 18 46 36 34]
[ 9 18]


# 6.How to get the dates of yesterday, today and tomorrow?

In [28]:
yest = np.datetime64('today', 'D') - np.timedelta64(1, 'D')

today = np.datetime64('today', 'D')

tom = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print (yest,'\n',today,'\n',tom,'\n')

2020-07-27 
 2020-07-28 
 2020-07-29 



# 7. Consider two random array A and B, check if they are equal

In [8]:
f1 = np.random.randint(0,2,5)

f2 = np.random.randint(0,2,5)

print (f1)
print (f2)

equal = np.array_equal(f1,f2)

print(equal)

[0 0 1 1 1]
[1 1 1 1 1]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [9]:
g = np.random.random(10)

print (g)

g[g.argmax()] = 0

print(g)

[0.75138721 0.78240045 0.60176154 0.40676673 0.23175847 0.12082019
 0.73610083 0.0553151  0.20027838 0.59900811]
[0.75138721 0.         0.60176154 0.40676673 0.23175847 0.12082019
 0.73610083 0.0553151  0.20027838 0.59900811]


# 9. How to print all the values of an array?

In [10]:
h = np.random.random((3,5))
print (h)


[[0.16722977 0.49984525 0.17503037 0.12731401 0.20807835]
 [0.81382198 0.31191533 0.80035599 0.42217377 0.15236193]
 [0.64587143 0.58745692 0.76289449 0.99088572 0.28576445]]


# 10.Subtract the mean of each row of a matrix

In [25]:
i = np.random.rand(2, 5)

i_new = i - i.mean(axis=1, keepdims=True)

print (i_new)

[[ 0.35474551 -0.33918133  0.04809573 -0.2018865   0.13822659]
 [-0.26338303  0.21884581 -0.3130697   0.57475991 -0.21715299]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
j = np.ones(10)

j_2nd = np.random.randint(0,len(j),15)

j += np.bincount(j_2nd, minlength=len(j))

print(j)

[3. 3. 2. 4. 1. 3. 2. 2. 2. 3.]


# 12.How to get the diagonal of a dot product?

In [24]:
k1 = np.random.randint(0,10,(5,5))

k2 = np.random.randint(0,10,(5,5))

k_diag = np.diag(np.dot(k1, k2))

k_diag

array([195,  99,  67, 167, 129])

# 13.How to find the most frequent value in an array?

In [23]:
l = np.random.randint(0,10,20)
print (l)
print(np.bincount(l).argmax())

[3 6 3 0 5 7 6 0 1 8 9 3 4 2 9 5 3 7 6 6]
3


# 14.How to get the n largest values of an array

In [15]:
# Not sure. Please guide.

# 15.How to create a record array from a regular array?

In [42]:
m = np.array([(4.2, 1.7, 5.9), (3.9, 1.3, 9.0)])

m_record = np.core.records.fromarrays(m.T, names='col1, col2, col3', formats = 'S8, f8, i8')

print(m_record)

[(b'4.2', 1.7, 5) (b'3.9', 1.3, 9)]
